//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Dotnet_BE_SOAP.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int INT_USUCODIGO { get; set; }
        public string VCH_USUNOMBRE { get; set; }
        public string VCH_USUAPELLIDO { get; set; }
        public string VCH_USUCEDULA { get; set; }
        public string VCH_USUDIRECCION { get; set; }
        public string VCH_USUTELEFONO { get; set; }
        public string VCH_USUEMAIL { get; set; }
        public string VCH_USUUSUARIO { get; set; }
        public string VCH_USUPASSWORD { get; set; }
    }
}
