//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDotnet_CoreBancario_SOAP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public int INT_CLIECODIGO { get; set; }
        public string VCH_CLIENOMBRE { get; set; }
        public string VCH_CLIEAPELLIDO { get; set; }
        public string VCH_CLIECEDULA { get; set; }
        public string VCH_CLIEDIRECCION { get; set; }
        public string VCH_CLIETELEFONO { get; set; }
        public string VCH_CLIEEMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA { get; set; }
    }
}
