//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDotnet_CoreBancario_SOAP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public int INT_CUENCODIGO { get; set; }
        public int INT_CLIECODIGO { get; set; }
        public string VCH_CUENNUMERO { get; set; }
        public string VCH_CUENTIPO { get; set; }
        public Nullable<decimal> DEC_CUENSALDO { get; set; }
        public Nullable<System.DateTime> DTT_CUENFECHACREACION { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
}
