//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDotnet_CoreBancario_SOAP.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int INT_MOVICODIGO { get; set; }
        public int INT_CUENCODIGO { get; set; }
        public Nullable<System.DateTime> DTT_MOVIFECHA { get; set; }
        public string VCH_MOVITIPO { get; set; }
        public Nullable<decimal> DEC_MOVIVALOR { get; set; }
        public Nullable<decimal> DEC_MOVISALDOFINAL { get; set; }
        public string VCH_MOVICUENTORIG { get; set; }
        public string VCH_MOVICUENTDEST { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
    }
}
