//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Dotnet_BE_SOAP.CoreBankService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int int_cliecodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_clienombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_clieapellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_cliecedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_cliedireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_clietelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vch_clieemailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int int_cliecodigo {
            get {
                return this.int_cliecodigoField;
            }
            set {
                if ((this.int_cliecodigoField.Equals(value) != true)) {
                    this.int_cliecodigoField = value;
                    this.RaisePropertyChanged("int_cliecodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string vch_clienombre {
            get {
                return this.vch_clienombreField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_clienombreField, value) != true)) {
                    this.vch_clienombreField = value;
                    this.RaisePropertyChanged("vch_clienombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vch_clieapellido {
            get {
                return this.vch_clieapellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_clieapellidoField, value) != true)) {
                    this.vch_clieapellidoField = value;
                    this.RaisePropertyChanged("vch_clieapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vch_cliecedula {
            get {
                return this.vch_cliecedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_cliecedulaField, value) != true)) {
                    this.vch_cliecedulaField = value;
                    this.RaisePropertyChanged("vch_cliecedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vch_cliedireccion {
            get {
                return this.vch_cliedireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_cliedireccionField, value) != true)) {
                    this.vch_cliedireccionField = value;
                    this.RaisePropertyChanged("vch_cliedireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string vch_clietelefono {
            get {
                return this.vch_clietelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_clietelefonoField, value) != true)) {
                    this.vch_clietelefonoField = value;
                    this.RaisePropertyChanged("vch_clietelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vch_clieemail {
            get {
                return this.vch_clieemailField;
            }
            set {
                if ((object.ReferenceEquals(this.vch_clieemailField, value) != true)) {
                    this.vch_clieemailField = value;
                    this.RaisePropertyChanged("vch_clieemail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int INT_CUENCODIGOField;
        
        private int INT_CLIECODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCH_CUENNUMEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCH_CUENTIPOField;
        
        private System.Nullable<decimal> DEC_CUENSALDOField;
        
        private System.Nullable<System.DateTime> DTT_CUENFECHACREACIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int INT_CUENCODIGO {
            get {
                return this.INT_CUENCODIGOField;
            }
            set {
                if ((this.INT_CUENCODIGOField.Equals(value) != true)) {
                    this.INT_CUENCODIGOField = value;
                    this.RaisePropertyChanged("INT_CUENCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int INT_CLIECODIGO {
            get {
                return this.INT_CLIECODIGOField;
            }
            set {
                if ((this.INT_CLIECODIGOField.Equals(value) != true)) {
                    this.INT_CLIECODIGOField = value;
                    this.RaisePropertyChanged("INT_CLIECODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCH_CUENNUMERO {
            get {
                return this.VCH_CUENNUMEROField;
            }
            set {
                if ((object.ReferenceEquals(this.VCH_CUENNUMEROField, value) != true)) {
                    this.VCH_CUENNUMEROField = value;
                    this.RaisePropertyChanged("VCH_CUENNUMERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCH_CUENTIPO {
            get {
                return this.VCH_CUENTIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCH_CUENTIPOField, value) != true)) {
                    this.VCH_CUENTIPOField = value;
                    this.RaisePropertyChanged("VCH_CUENTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DEC_CUENSALDO {
            get {
                return this.DEC_CUENSALDOField;
            }
            set {
                if ((this.DEC_CUENSALDOField.Equals(value) != true)) {
                    this.DEC_CUENSALDOField = value;
                    this.RaisePropertyChanged("DEC_CUENSALDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> DTT_CUENFECHACREACION {
            get {
                return this.DTT_CUENFECHACREACIONField;
            }
            set {
                if ((this.DTT_CUENFECHACREACIONField.Equals(value) != true)) {
                    this.DTT_CUENFECHACREACIONField = value;
                    this.RaisePropertyChanged("DTT_CUENFECHACREACION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int INT_MOVICODIGOField;
        
        private int INT_CUENCODIGOField;
        
        private System.Nullable<System.DateTime> DTT_MOVIFECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCH_MOVITIPOField;
        
        private System.Nullable<decimal> DEC_MOVIVALORField;
        
        private System.Nullable<decimal> DEC_MOVISALDOFINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCH_MOVICUENTORIGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCH_MOVICUENTDESTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int INT_MOVICODIGO {
            get {
                return this.INT_MOVICODIGOField;
            }
            set {
                if ((this.INT_MOVICODIGOField.Equals(value) != true)) {
                    this.INT_MOVICODIGOField = value;
                    this.RaisePropertyChanged("INT_MOVICODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int INT_CUENCODIGO {
            get {
                return this.INT_CUENCODIGOField;
            }
            set {
                if ((this.INT_CUENCODIGOField.Equals(value) != true)) {
                    this.INT_CUENCODIGOField = value;
                    this.RaisePropertyChanged("INT_CUENCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> DTT_MOVIFECHA {
            get {
                return this.DTT_MOVIFECHAField;
            }
            set {
                if ((this.DTT_MOVIFECHAField.Equals(value) != true)) {
                    this.DTT_MOVIFECHAField = value;
                    this.RaisePropertyChanged("DTT_MOVIFECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCH_MOVITIPO {
            get {
                return this.VCH_MOVITIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.VCH_MOVITIPOField, value) != true)) {
                    this.VCH_MOVITIPOField = value;
                    this.RaisePropertyChanged("VCH_MOVITIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> DEC_MOVIVALOR {
            get {
                return this.DEC_MOVIVALORField;
            }
            set {
                if ((this.DEC_MOVIVALORField.Equals(value) != true)) {
                    this.DEC_MOVIVALORField = value;
                    this.RaisePropertyChanged("DEC_MOVIVALOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> DEC_MOVISALDOFINAL {
            get {
                return this.DEC_MOVISALDOFINALField;
            }
            set {
                if ((this.DEC_MOVISALDOFINALField.Equals(value) != true)) {
                    this.DEC_MOVISALDOFINALField = value;
                    this.RaisePropertyChanged("DEC_MOVISALDOFINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCH_MOVICUENTORIG {
            get {
                return this.VCH_MOVICUENTORIGField;
            }
            set {
                if ((object.ReferenceEquals(this.VCH_MOVICUENTORIGField, value) != true)) {
                    this.VCH_MOVICUENTORIGField = value;
                    this.RaisePropertyChanged("VCH_MOVICUENTORIG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VCH_MOVICUENTDEST {
            get {
                return this.VCH_MOVICUENTDESTField;
            }
            set {
                if ((object.ReferenceEquals(this.VCH_MOVICUENTDESTField, value) != true)) {
                    this.VCH_MOVICUENTDESTField = value;
                    this.RaisePropertyChanged("VCH_MOVICUENTDEST");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreBankService.CoreBankServiceSoap")]
    public interface CoreBankServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse HelloWorld(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse> HelloWorldAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarCliente", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse buscarCliente(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse> buscarClienteAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest request);
        
        // CODEGEN: Generating message contract since element name cedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCuentas", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse obtenerCuentas(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCuentas", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse> obtenerCuentasAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerMovimientos", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse obtenerMovimientos(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse> obtenerMovimientosAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest request);
        
        // CODEGEN: Generating message contract since element name cuentaOrig from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transferirDinero", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse transferirDinero(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transferirDinero", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse> transferirDineroAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerSaldoCuenta", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse obtenerSaldoCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerSaldoCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse> obtenerSaldoCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerClienteDestino", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse obtenerClienteDestino(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerClienteDestino", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse> obtenerClienteDestinoAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarCuenta", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse validarCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse> validarCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest request);
        
        // CODEGEN: Generating message contract since element name cuenta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCuenta", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse obtenerCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse> obtenerCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest request);
        
        // CODEGEN: Generating message contract since element name obtenerClienteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCliente", ReplyAction="*")]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse obtenerCliente(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse> obtenerClienteAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequestBody Body;
        
        public buscarClienteRequest() {
        }
        
        public buscarClienteRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuenta;
        
        public buscarClienteRequestBody() {
        }
        
        public buscarClienteRequestBody(string cedula, string cuenta) {
            this.cedula = cedula;
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponseBody Body;
        
        public buscarClienteResponse() {
        }
        
        public buscarClienteResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente buscarClienteResult;
        
        public buscarClienteResponseBody() {
        }
        
        public buscarClienteResponseBody(Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente buscarClienteResult) {
            this.buscarClienteResult = buscarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCuentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCuentas", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequestBody Body;
        
        public obtenerCuentasRequest() {
        }
        
        public obtenerCuentasRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCuentasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public obtenerCuentasRequestBody() {
        }
        
        public obtenerCuentasRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCuentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCuentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponseBody Body;
        
        public obtenerCuentasResponse() {
        }
        
        public obtenerCuentasResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCuentasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta> obtenerCuentasResult;
        
        public obtenerCuentasResponseBody() {
        }
        
        public obtenerCuentasResponseBody(System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta> obtenerCuentasResult) {
            this.obtenerCuentasResult = obtenerCuentasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMovimientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMovimientos", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequestBody Body;
        
        public obtenerMovimientosRequest() {
        }
        
        public obtenerMovimientosRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerMovimientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public obtenerMovimientosRequestBody() {
        }
        
        public obtenerMovimientosRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerMovimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerMovimientosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponseBody Body;
        
        public obtenerMovimientosResponse() {
        }
        
        public obtenerMovimientosResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerMovimientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Movimiento> obtenerMovimientosResult;
        
        public obtenerMovimientosResponseBody() {
        }
        
        public obtenerMovimientosResponseBody(System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Movimiento> obtenerMovimientosResult) {
            this.obtenerMovimientosResult = obtenerMovimientosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferirDineroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transferirDinero", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequestBody Body;
        
        public transferirDineroRequest() {
        }
        
        public transferirDineroRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferirDineroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaOrig;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cuentaDest;
        
        public transferirDineroRequestBody() {
        }
        
        public transferirDineroRequestBody(string cuentaOrig, double monto, string cuentaDest) {
            this.cuentaOrig = cuentaOrig;
            this.monto = monto;
            this.cuentaDest = cuentaDest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferirDineroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transferirDineroResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponseBody Body;
        
        public transferirDineroResponse() {
        }
        
        public transferirDineroResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferirDineroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool transferirDineroResult;
        
        public transferirDineroResponseBody() {
        }
        
        public transferirDineroResponseBody(bool transferirDineroResult) {
            this.transferirDineroResult = transferirDineroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerSaldoCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerSaldoCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequestBody Body;
        
        public obtenerSaldoCuentaRequest() {
        }
        
        public obtenerSaldoCuentaRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerSaldoCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public obtenerSaldoCuentaRequestBody() {
        }
        
        public obtenerSaldoCuentaRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerSaldoCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerSaldoCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponseBody Body;
        
        public obtenerSaldoCuentaResponse() {
        }
        
        public obtenerSaldoCuentaResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerSaldoCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double obtenerSaldoCuentaResult;
        
        public obtenerSaldoCuentaResponseBody() {
        }
        
        public obtenerSaldoCuentaResponseBody(double obtenerSaldoCuentaResult) {
            this.obtenerSaldoCuentaResult = obtenerSaldoCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerClienteDestinoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerClienteDestino", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequestBody Body;
        
        public obtenerClienteDestinoRequest() {
        }
        
        public obtenerClienteDestinoRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerClienteDestinoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public obtenerClienteDestinoRequestBody() {
        }
        
        public obtenerClienteDestinoRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerClienteDestinoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerClienteDestinoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponseBody Body;
        
        public obtenerClienteDestinoResponse() {
        }
        
        public obtenerClienteDestinoResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerClienteDestinoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerClienteDestinoResult;
        
        public obtenerClienteDestinoResponseBody() {
        }
        
        public obtenerClienteDestinoResponseBody(Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerClienteDestinoResult) {
            this.obtenerClienteDestinoResult = obtenerClienteDestinoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequestBody Body;
        
        public validarCuentaRequest() {
        }
        
        public validarCuentaRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public validarCuentaRequestBody() {
        }
        
        public validarCuentaRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponseBody Body;
        
        public validarCuentaResponse() {
        }
        
        public validarCuentaResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validarCuentaResult;
        
        public validarCuentaResponseBody() {
        }
        
        public validarCuentaResponseBody(bool validarCuentaResult) {
            this.validarCuentaResult = validarCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequestBody Body;
        
        public obtenerCuentaRequest() {
        }
        
        public obtenerCuentaRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public obtenerCuentaRequestBody() {
        }
        
        public obtenerCuentaRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponseBody Body;
        
        public obtenerCuentaResponse() {
        }
        
        public obtenerCuentaResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta obtenerCuentaResult;
        
        public obtenerCuentaResponseBody() {
        }
        
        public obtenerCuentaResponseBody(Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta obtenerCuentaResult) {
            this.obtenerCuentaResult = obtenerCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequestBody Body;
        
        public obtenerClienteRequest() {
        }
        
        public obtenerClienteRequest(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num;
        
        public obtenerClienteRequestBody() {
        }
        
        public obtenerClienteRequestBody(int num) {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponseBody Body;
        
        public obtenerClienteResponse() {
        }
        
        public obtenerClienteResponse(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerClienteResult;
        
        public obtenerClienteResponseBody() {
        }
        
        public obtenerClienteResponseBody(Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerClienteResult) {
            this.obtenerClienteResult = obtenerClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreBankServiceSoapChannel : Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreBankServiceSoapClient : System.ServiceModel.ClientBase<Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap>, Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap {
        
        public CoreBankServiceSoapClient() {
        }
        
        public CoreBankServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreBankServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBankServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBankServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.HelloWorld(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequestBody();
            Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.HelloWorldAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldResponse> HelloWorldAsync() {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.HelloWorldRequestBody();
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.buscarCliente(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest request) {
            return base.Channel.buscarCliente(request);
        }
        
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente buscarCliente(string cedula, string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).buscarCliente(inValue);
            return retVal.Body.buscarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.buscarClienteAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest request) {
            return base.Channel.buscarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteResponse> buscarClienteAsync(string cedula, string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.buscarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).buscarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerCuentas(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest request) {
            return base.Channel.obtenerCuentas(request);
        }
        
        public System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta> obtenerCuentas(string cedula) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequestBody();
            inValue.Body.cedula = cedula;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerCuentas(inValue);
            return retVal.Body.obtenerCuentasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerCuentasAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest request) {
            return base.Channel.obtenerCuentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasResponse> obtenerCuentasAsync(string cedula) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentasRequestBody();
            inValue.Body.cedula = cedula;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerCuentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerMovimientos(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest request) {
            return base.Channel.obtenerMovimientos(request);
        }
        
        public System.Collections.Generic.List<Proyecto_Dotnet_BE_SOAP.CoreBankService.Movimiento> obtenerMovimientos(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerMovimientos(inValue);
            return retVal.Body.obtenerMovimientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerMovimientosAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest request) {
            return base.Channel.obtenerMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosResponse> obtenerMovimientosAsync(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerMovimientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.transferirDinero(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest request) {
            return base.Channel.transferirDinero(request);
        }
        
        public bool transferirDinero(string cuentaOrig, double monto, string cuentaDest) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequestBody();
            inValue.Body.cuentaOrig = cuentaOrig;
            inValue.Body.monto = monto;
            inValue.Body.cuentaDest = cuentaDest;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).transferirDinero(inValue);
            return retVal.Body.transferirDineroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.transferirDineroAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest request) {
            return base.Channel.transferirDineroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroResponse> transferirDineroAsync(string cuentaOrig, double monto, string cuentaDest) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.transferirDineroRequestBody();
            inValue.Body.cuentaOrig = cuentaOrig;
            inValue.Body.monto = monto;
            inValue.Body.cuentaDest = cuentaDest;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).transferirDineroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerSaldoCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest request) {
            return base.Channel.obtenerSaldoCuenta(request);
        }
        
        public double obtenerSaldoCuenta(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerSaldoCuenta(inValue);
            return retVal.Body.obtenerSaldoCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerSaldoCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest request) {
            return base.Channel.obtenerSaldoCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaResponse> obtenerSaldoCuentaAsync(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerSaldoCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerSaldoCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerClienteDestino(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest request) {
            return base.Channel.obtenerClienteDestino(request);
        }
        
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerClienteDestino(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequestBody();
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerClienteDestino(inValue);
            return retVal.Body.obtenerClienteDestinoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerClienteDestinoAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest request) {
            return base.Channel.obtenerClienteDestinoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoResponse> obtenerClienteDestinoAsync(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteDestinoRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerClienteDestinoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.validarCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest request) {
            return base.Channel.validarCuenta(request);
        }
        
        public bool validarCuenta(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).validarCuenta(inValue);
            return retVal.Body.validarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.validarCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest request) {
            return base.Channel.validarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaResponse> validarCuentaAsync(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.validarCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).validarCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerCuenta(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest request) {
            return base.Channel.obtenerCuenta(request);
        }
        
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cuenta obtenerCuenta(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerCuenta(inValue);
            return retVal.Body.obtenerCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerCuentaAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest request) {
            return base.Channel.obtenerCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaResponse> obtenerCuentaAsync(string cuenta) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerCuentaRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerCliente(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest request) {
            return base.Channel.obtenerCliente(request);
        }
        
        public Proyecto_Dotnet_BE_SOAP.CoreBankService.Cliente obtenerCliente(int num) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequestBody();
            inValue.Body.num = num;
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse retVal = ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerCliente(inValue);
            return retVal.Body.obtenerClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse> Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap.obtenerClienteAsync(Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest request) {
            return base.Channel.obtenerClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteResponse> obtenerClienteAsync(int num) {
            Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest inValue = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequest();
            inValue.Body = new Proyecto_Dotnet_BE_SOAP.CoreBankService.obtenerClienteRequestBody();
            inValue.Body.num = num;
            return ((Proyecto_Dotnet_BE_SOAP.CoreBankService.CoreBankServiceSoap)(this)).obtenerClienteAsync(inValue);
        }
    }
}
